version: "3.8"

services:

  classifier:
    build: .
    volumes:
      - .:/app
    container_name: classifier
    ports:
      - ${API_PORT}:5000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'
    restart: always
